version: '2'
services:
  postgres:
    image: sameersbn/postgresql
    container_name: pgsql_ginapi
    ports:
    - "5432:5432"
    environment:
      - DB_USER=developer
      - DB_PASS=developer
      - DB_NAME=ginapi_dev
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
